# If src has been changed package re-builded and
# in case dist has changed, changes are committed.

name: ✨ Rebuild and commit dist
run-name: Rebuild

on:
  push:
    paths:
      - src/**

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: '7'

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Check if dist has changed
        id: check
        run: |
          git diff --quiet --exit-code -- dist
        continue-on-error: true

      - name: Commit files
        if: ${{ steps.check.outcome != 'success' }}
        run: |
          git config --local user.email "buildaction@bot.bot"
          git config --local user.name "bot"
          git commit -am "chore: build action bot"
          git push
