name: CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: muravjev/gha-setup-pnpm@main
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: muravjev/gha-setup-pnpm@main
      - run: pnpm fix
      - run: git diff --quiet --exit-code
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: muravjev/gha-setup-pnpm@main
      - run: pnpm build
      - run: git diff --quiet --exit-code -- dist
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: muravjev/gha-setup-pnpm@main
      - run: pnpm repos:restore
      - run: pnpm test
  finish:
    runs-on: ubuntu-latest
    needs: [lint, build, test]
    steps:
      - run: echo '## ✔ Success' >> $GITHUB_STEP_SUMMARY
